# Generated by Django 5.2.5 on 2025-08-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='last_name',
        ),
        migrations.AddField(
            model_name='parent',
            name='full_name',
            field=models.CharField(default='Unknown user', max_length=100),
            preserve_default=False,
        ),
    ]
