# Generated by Django 5.2.5 on 2025-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_familyinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinvitation',
            name='invitation_id',
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invitation_code',
            field=models.CharField(default='TEMP_CODE', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
