# Generated by Django 5.2.5 on 2025-08-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_familyinvitation_invitation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('child_name', models.CharField(max_length=100)),
                ('family_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'child_registration_codes',
            },
        ),
    ]
